format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$time\
[ ](fg:#394260)\
\n[░▒▓](#394260)\
[  ](bg:#394260 fg:#9eceff)\
[](fg:#394260 bg:#2f3b5c)\
$nodejs\
$python\
$java\
$golang\
$terraform\
$docker_context\
$kubernetes\
$cmd_duration\
$jobs\
$status\
[ ](fg:#2f3b5c)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#2f3b5c"
format = '[[ $symbol ($version) ](fg:#c0caf5 bg:#2f3b5c)]($style)'

[python]
symbol = ""
style = "bg:#2f3b5c"
format = '[[ $symbol ($version) ](fg:#c0caf5 bg:#2f3b5c)]($style)'

[java]
symbol = ""
style = "bg:#2f3b5c"
format = '[[ $symbol ($version) ](fg:#c0caf5 bg:#2f3b5c)]($style)'

[golang]
symbol = "󰟓"
style = "bg:#2f3b5c"
format = '[[ $symbol ($version) ](fg:#c0caf5 bg:#2f3b5c)]($style)'

[terraform]
symbol = "󱁢"
style = "bg:#2f3b5c"
format = '[[ $symbol $workspace ](fg:#c0caf5 bg:#2f3b5c)]($style)'

[docker_context]
symbol = ""
style = "bg:#2f3b5c"
format = '[[ $symbol $context ](fg:#c0caf5 bg:#2f3b5c)]($style)'

[kubernetes]
disabled = false
symbol = "󱃾"
style = "bg:#2f3b5c"
format = '[[ $symbol $context( \($namespace\)) ](fg:#c0caf5 bg:#2f3b5c)]($style)'

[cmd_duration]
min_time = 2000
style = "bg:#2f3b5c"
format = '[[  $duration ](fg:#c0caf5 bg:#2f3b5c)]($style)'

[jobs]
symbol = ""
style = "bg:#2f3b5c"
format = '[[ $symbol $number ](fg:#c0caf5 bg:#2f3b5c)]($style)'

[status]
disabled = false
symbol = "[✘](fg:#ff9eaf bg:#2f3b5c)"
success_symbol = "[✔](fg:#9ece6a bg:#2f3b5c)"
style = "bg:#2f3b5c"
format = '[[ $symbol $status ](fg:#c0caf5 bg:#2f3b5c)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#394260"
format = '[[  $time ](fg:#c0caf5 bg:#394260)]($style)'
